import Foundation
import AppKit

enum ClipboardMonitoringConsent: String, CaseIterable, Sendable {
    case undecided
    case enabled
    case disabled
}

@MainActor
final class ClipboardPreferences: ObservableObject {
    static let shared = ClipboardPreferences()

    private enum Key {
        static let consent = "clipboardMonitoringConsent"
        static let legacyEnabled = "clipboardMonitoringEnabled"
        static let retentionCount = "clipboardRetentionCount"
        static let retentionDays = "clipboardRetentionDays"
    }

    private let defaults: UserDefaults
    @Published private(set) var consent: ClipboardMonitoringConsent
    @Published private(set) var retentionCount: Int
    @Published private(set) var retentionDays: Int

    init(defaults: UserDefaults = .standard) {
        self.defaults = defaults
        if let rawConsent = defaults.string(forKey: Key.consent),
           let storedConsent = ClipboardMonitoringConsent(rawValue: rawConsent) {
            consent = storedConsent
        } else if let legacyEnabled = defaults.object(forKey: Key.legacyEnabled) as? Bool {
            let migratedConsent: ClipboardMonitoringConsent = legacyEnabled ? .enabled : .disabled
            consent = migratedConsent
            defaults.set(migratedConsent.rawValue, forKey: Key.consent)
            defaults.removeObject(forKey: Key.legacyEnabled)
        } else {
            consent = .undecided
        }

        let storedCount = defaults.object(forKey: Key.retentionCount) as? Int
        retentionCount = storedCount.flatMap { [0, 50, 100, 200].contains($0) ? $0 : nil } ?? 100
        let storedDays = defaults.object(forKey: Key.retentionDays) as? Int
        retentionDays = storedDays.flatMap { [0, 1, 7, 30].contains($0) ? $0 : nil } ?? 30
    }

    var retentionPolicy: ClipboardRetentionPolicy {
        ClipboardRetentionPolicy(
            maximumItemCount: retentionCount == 0 ? nil : retentionCount,
            maximumAgeDays: retentionDays == 0 ? nil : retentionDays
        )
    }

    func setConsent(_ newValue: ClipboardMonitoringConsent) {
        consent = newValue
        defaults.set(newValue.rawValue, forKey: Key.consent)
    }

    func setRetentionCount(_ count: Int) {
        guard [0, 50, 100, 200].contains(count) else { return }
        retentionCount = count
        defaults.set(count, forKey: Key.retentionCount)
    }

    func setRetentionDays(_ days: Int) {
        guard [0, 1, 7, 30].contains(days) else { return }
        retentionDays = days
        defaults.set(days, forKey: Key.retentionDays)
    }
}

enum ClipboardPayloadRead: Sendable {
    case none
    case ignored
    case text(String)
    case pendingImage(fallbackText: String?, failureMessage: String? = nil)
    case image(Data, fileExtension: String)
    case rejected(String)
}

struct ClipboardPayloadSnapshot: Sendable {
    let changeCount: Int
    let payload: ClipboardPayloadRead
}

protocol ClipboardPasteboard: Sendable {
    @MainActor var changeCount: Int { get }
    func readPayloadSnapshot(
        maximumImageBytes: Int,
        maximumTextCharacters: Int
    ) -> ClipboardPayloadSnapshot?
}

final class SystemClipboardPasteboard: ClipboardPasteboard, @unchecked Sendable {
    private struct HelperReadBudget {
        let perFlavorTimeout: TimeInterval
        let deadlineUptime: TimeInterval
    }

    static let shared = SystemClipboardPasteboard()
    private static let maximumTextBytes = 16 * 1_024 * 1_024
    private static let maximumImageRepresentations = 8
    private static let ignoredTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType")
    ]
    private let pasteboard: NSPasteboard
    private let pasteboardName: String
    private let helperClient: ClipboardPasteboardHelperClient
    private let helperAttemptLock = NSLock()
    private var helperReadAttempts: [Int: Int] = [:]
    private var helperReadAttemptOrder: [Int] = []

    init(
        pasteboard: NSPasteboard = .general,
        helperClient: ClipboardPasteboardHelperClient = ClipboardPasteboardHelperClient()
    ) {
        self.pasteboard = pasteboard
        pasteboardName = pasteboard.name.rawValue
        self.helperClient = helperClient
    }

    @MainActor var changeCount: Int { pasteboard.changeCount }

    func readPayloadSnapshot(
        maximumImageBytes: Int,
        maximumTextCharacters: Int
    ) -> ClipboardPayloadSnapshot? {
        // Providers can update the pasteboard while materializing data. Retry a changing read so
        // every accepted payload is tied to the exact stable changeCount that produced it.
        let helperBudget = helperReadBudget(for: pasteboard.changeCount)
        for _ in 0..<3 {
            let before = pasteboard.changeCount
            let beforeTypes = pasteboard.types?.map(\.rawValue).sorted() ?? []
            let payload = readPayload(
                expectedChangeCount: before,
                declaredTypes: beforeTypes.map { NSPasteboard.PasteboardType($0) },
                maximumImageBytes: maximumImageBytes,
                maximumTextCharacters: maximumTextCharacters,
                helperBudget: helperBudget
            )
            let after = pasteboard.changeCount
            let afterTypes = pasteboard.types?.map(\.rawValue).sorted() ?? []
            if before == after, beforeTypes == afterTypes {
                return ClipboardPayloadSnapshot(changeCount: after, payload: payload)
            }
        }
        return nil
    }

    private func readPayload(
        expectedChangeCount: Int,
        declaredTypes: [NSPasteboard.PasteboardType],
        maximumImageBytes: Int,
        maximumTextCharacters: Int,
        helperBudget: HelperReadBudget
    ) -> ClipboardPayloadRead {
        guard !declaredTypes.contains(where: Self.ignoredTypes.contains) else { return .ignored }

        // Pasteboard providers are synchronous and cannot be cancelled in-process. Each flavor is
        // materialized by a killable helper process so one broken provider cannot consume a reader
        // lane forever or prevent a ready fallback representation from being tried.
        let imageTypes = Self.imageTypes(from: declaredTypes)
        var imageReadError: Error?
        var sawOversizedSource = false
        var sawOversizedOutput = false
        var sawIncompleteSource = false
        var sawPendingFlavor = false
        for type in imageTypes {
            guard let flavorTimeout = remainingHelperTimeout(in: helperBudget) else {
                sawPendingFlavor = true
                break
            }
            let helperRead = helperClient.read(
                pasteboardName: pasteboardName,
                type: type.rawValue,
                expectedChangeCount: expectedChangeCount,
                mode: .data,
                maximumBytes: ClipboardPNGEncoder.maximumSourceBytes,
                timeout: flavorTimeout
            )
            let sourceData: Data
            switch helperRead {
            case .value(let data):
                sourceData = data
            case .unavailable, .unstable, .timedOut:
                sawPendingFlavor = true
                continue
            case .oversized:
                sawOversizedSource = true
                continue
            case .failed:
                imageReadError = CocoaError(.fileReadUnknown)
                continue
            }
            do {
                let pngData = try ClipboardPNGEncoder.pngData(
                    from: sourceData,
                    maximumOutputBytes: maximumImageBytes
                )
                return .image(pngData, fileExtension: "png")
            } catch ClipboardPNGEncodingError.outputTooLarge {
                sawOversizedOutput = true
            } catch ClipboardPNGEncodingError.sourceIncomplete {
                sawIncompleteSource = true
            } catch {
                imageReadError = error
            }
        }
        let textRead = readText(
            expectedChangeCount: expectedChangeCount,
            declaredTypes: declaredTypes,
            maximumCharacters: maximumTextCharacters,
            helperBudget: helperBudget
        )
        let fallbackText = textRead.content
        let imageFailureMessage: String?
        if sawOversizedOutput {
            imageFailureMessage = "剪贴板图片转换为 PNG 后超过 50 MB，已跳过"
        } else if sawOversizedSource {
            imageFailureMessage = "剪贴板图片源数据超过 256 MB，已跳过"
        } else if imageReadError != nil {
            imageFailureMessage = "无法解码剪贴板图片，已跳过"
        } else if sawIncompleteSource {
            imageFailureMessage = "剪贴板图片始终未完整提供，已跳过"
        } else {
            imageFailureMessage = nil
        }
        let textFailureMessage: String?
        if textRead.wasOversized {
            textFailureMessage = "剪贴板文本超过 100 万字符，已跳过"
        } else if textRead.helperFailed {
            textFailureMessage = "剪贴板读取组件不可用，已跳过"
        } else {
            textFailureMessage = nil
        }
        if sawIncompleteSource || sawPendingFlavor || (textRead.sawPending && fallbackText == nil) {
            let pendingFailure: String
            if !imageTypes.isEmpty && (sawIncompleteSource || sawPendingFlavor) {
                pendingFailure = imageFailureMessage ?? "剪贴板图片提供方长时间未返回，已跳过"
            } else {
                pendingFailure = imageFailureMessage
                    ?? textFailureMessage
                    ?? "剪贴板内容提供方长时间未返回，已跳过"
            }
            return .pendingImage(
                fallbackText: fallbackText,
                failureMessage: pendingFailure
            )
        }
        if let fallbackText {
            return .text(fallbackText)
        }
        if let imageFailureMessage {
            return .rejected(imageFailureMessage)
        }
        if !imageTypes.isEmpty {
            return .pendingImage(
                fallbackText: nil,
                failureMessage: "剪贴板图片提供方长时间未返回，已跳过"
            )
        }
        if let textFailureMessage {
            return .rejected(textFailureMessage)
        }
        return .none
    }

    private func readText(
        expectedChangeCount: Int,
        declaredTypes: [NSPasteboard.PasteboardType],
        maximumCharacters: Int,
        helperBudget: HelperReadBudget
    ) -> (content: String?, wasOversized: Bool, helperFailed: Bool, sawPending: Bool) {
        var wasOversized = false
        var helperFailed = false
        var sawPending = false
        for type in [NSPasteboard.PasteboardType.URL, .string] where declaredTypes.contains(type) {
            guard let flavorTimeout = remainingHelperTimeout(in: helperBudget) else {
                sawPending = true
                break
            }
            switch helperClient.read(
                pasteboardName: pasteboardName,
                type: type.rawValue,
                expectedChangeCount: expectedChangeCount,
                mode: .string,
                maximumBytes: Self.maximumTextBytes,
                timeout: flavorTimeout
            ) {
            case .value(let data):
                guard let content = String(data: data, encoding: .utf8), !content.isEmpty else {
                    continue
                }
                guard content.count <= maximumCharacters else {
                    wasOversized = true
                    continue
                }
                return (content, wasOversized, helperFailed, sawPending)
            case .oversized:
                wasOversized = true
            case .failed:
                helperFailed = true
            case .unavailable, .unstable, .timedOut:
                sawPending = true
            }
        }
        return (nil, wasOversized, helperFailed, sawPending)
    }

    private func helperReadBudget(for changeCount: Int) -> HelperReadBudget {
        helperAttemptLock.withLock {
            let attempt = (helperReadAttempts[changeCount] ?? 0) + 1
            if helperReadAttempts[changeCount] == nil {
                helperReadAttemptOrder.append(changeCount)
            }
            helperReadAttempts[changeCount] = attempt
            while helperReadAttemptOrder.count > 32 {
                let expiredCount = helperReadAttemptOrder.removeFirst()
                helperReadAttempts[expiredCount] = nil
            }
            let perFlavorTimeout: TimeInterval
            let totalTimeout: TimeInterval
            switch attempt {
            case 1...2:
                perFlavorTimeout = 0.75
                totalTimeout = 1.25
            case 3...5:
                perFlavorTimeout = 1.25
                totalTimeout = 1.75
            default:
                perFlavorTimeout = 1.75
                totalTimeout = 2
            }
            return HelperReadBudget(
                perFlavorTimeout: perFlavorTimeout,
                deadlineUptime: ProcessInfo.processInfo.systemUptime + totalTimeout
            )
        }
    }

    private func remainingHelperTimeout(in budget: HelperReadBudget) -> TimeInterval? {
        let remaining = budget.deadlineUptime - ProcessInfo.processInfo.systemUptime
        guard remaining >= 0.05 else { return nil }
        return min(budget.perFlavorTimeout, remaining)
    }

    private static func imageTypes(
        from declaredTypes: [NSPasteboard.PasteboardType]
    ) -> [NSPasteboard.PasteboardType] {
        var result: [NSPasteboard.PasteboardType] = []
        var seen = Set<NSPasteboard.PasteboardType>()
        for type in [NSPasteboard.PasteboardType.png, .tiff] + declaredTypes {
            guard !seen.contains(type),
                  declaredTypes.contains(type),
                  ClipboardPNGEncoder.isImageType(type) else { continue }
            seen.insert(type)
            result.append(type)
            if result.count == maximumImageRepresentations { break }
        }
        return result
    }
}

typealias ClipboardImageSaver = @Sendable (Data, String, Date) async throws -> StashItem
typealias ClipboardImageDiscarder = @Sendable (StashItem) async -> Void

private struct ClipboardReadRequest: Sendable, Equatable {
    let id: UUID
    let generation: UInt64
    let changeCount: Int
    let observedAt: Date
}

private struct ClipboardProvisionalText: Sendable {
    let content: String
    let request: ClipboardReadRequest
}

@MainActor
final class ClipboardMonitor: ObservableObject {
    static let shared = ClipboardMonitor()
    private static let maximumImageBytes = 50 * 1024 * 1024
    private static let maximumTextCharacters = 1_000_000
    private static let maximumRememberedChangeCounts = 256
    private static let maximumEmptySnapshotRetries = 12
    private static let maximumImageSaveRetries = 2
    private static let maximumConcurrentPayloadReads = 2
    private static let payloadSettleNanoseconds: UInt64 = 25_000_000

    private let preferences: ClipboardPreferences
    private let pasteboard: ClipboardPasteboard
    private let imageSaver: ClipboardImageSaver
    private let imageDiscarder: ClipboardImageDiscarder
    private let payloadReaderQueue: DispatchQueue
    private let payloadReadGroup = DispatchGroup()
    private let pollingInterval: TimeInterval
    private let readTimeoutInterval: TimeInterval
    private var changeCount: Int
    private var generation: UInt64 = 0
    private var inFlightRead: ClipboardReadRequest?
    private var pendingRead: ClipboardReadRequest?
    private var outstandingReads: [UUID: ClipboardReadRequest] = [:]
    private var settleReadRequest: ClipboardReadRequest?
    private var settleReadTask: Task<Void, Never>?
    private var readTimeoutTask: Task<Void, Never>?
    private var imageSaveTasks: [UUID: Task<Void, Never>] = [:]
    private var rememberedChangeCounts = Set<Int>()
    private var rememberedChangeCountOrder: [Int] = []
    private var emptySnapshotRetryAttempts: [Int: Int] = [:]
    private var pendingFailureMessages: [Int: String] = [:]
    private var snapshotRetryTasks: [Int: Task<Void, Never>] = [:]
    private var provisionalTexts: [Int: ClipboardProvisionalText] = [:]
    private var preparedImages: [UUID: StashItem] = [:]
    private var timer: Timer?
    private var isStopped = false
    private var isGracefullyShuttingDown = false
    var onNewItem: ((StashItem) -> Void)?
    var onError: ((String) -> Void)?
    @Published private(set) var consent: ClipboardMonitoringConsent

    var isEnabled: Bool { consent == .enabled }

    init(
        preferences: ClipboardPreferences? = nil,
        pasteboard: ClipboardPasteboard? = nil,
        payloadReaderQueue: DispatchQueue? = nil,
        pollingInterval: TimeInterval = 0.25,
        readTimeoutInterval: TimeInterval = 2,
        imageSaver: ClipboardImageSaver? = nil,
        imageDiscarder: ClipboardImageDiscarder? = nil
    ) {
        let resolvedPreferences = preferences ?? ClipboardPreferences.shared
        let resolvedPasteboard = pasteboard ?? SystemClipboardPasteboard.shared
        self.preferences = resolvedPreferences
        self.pasteboard = resolvedPasteboard
        self.payloadReaderQueue = payloadReaderQueue ?? DispatchQueue(
            label: "com.quickstash.clipboard-reader",
            qos: .utility,
            attributes: .concurrent
        )
        self.pollingInterval = max(0.05, pollingInterval)
        self.readTimeoutInterval = max(0.05, readTimeoutInterval)
        self.imageSaver = imageSaver ?? { data, fileExtension, observedAt in
            try await QuickStashFileManager.shared.saveClipboardImage(
                data: data,
                fileExtension: fileExtension,
                createdAt: observedAt
            )
        }
        self.imageDiscarder = imageDiscarder ?? { item in
            await QuickStashFileManager.shared.discardUnregisteredClipboardImage(at: item.content)
        }
        consent = resolvedPreferences.consent
        changeCount = resolvedPasteboard.changeCount
        rememberChangeCount(changeCount)
    }

    var retentionPolicy: ClipboardRetentionPolicy { preferences.retentionPolicy }
    var retentionCount: Int { preferences.retentionCount }
    var retentionDays: Int { preferences.retentionDays }

    func startMonitoring() {
        guard timer == nil else { return }
        let wasStopped = isStopped
        isStopped = false
        if wasStopped {
            resetChangeTracking(to: pasteboard.changeCount)
        }
        let timer = Timer(timeInterval: pollingInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.checkClipboard() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stopMonitoring() {
        isStopped = true
        timer?.invalidate()
        timer = nil
        invalidatePendingCaptures()
    }

    func shutdownAndDrain(
        waitForPayloadReads: Bool = false,
        payloadReadDrainTimeout: TimeInterval = 1
    ) async {
        stopMonitoring()
        if waitForPayloadReads {
            await drainPayloadReads(timeout: payloadReadDrainTimeout)
        }
        while !imageSaveTasks.isEmpty {
            let tasks = Array(imageSaveTasks.values)
            for task in tasks {
                await task.value
            }
        }
        let abandonedPreparedImages = Array(preparedImages.values)
        preparedImages.removeAll(keepingCapacity: false)
        for item in abandonedPreparedImages {
            await imageDiscarder(item)
        }
    }

    func shutdownForTermination(
        settleNanoseconds: UInt64 = 400_000_000
    ) async {
        guard !isStopped else {
            await shutdownAndDrain()
            return
        }

        // Stop periodic polling, but give the final observed pasteboard change a short async
        // window to materialize. This never blocks MainActor or waits indefinitely on a provider.
        timer?.invalidate()
        timer = nil
        checkClipboard()
        if settleNanoseconds > 0 {
            try? await Task.sleep(nanoseconds: settleNanoseconds)
        }

        isGracefullyShuttingDown = true
        isStopped = true
        settleReadTask?.cancel()
        settleReadTask = nil
        settleReadRequest = nil
        readTimeoutTask?.cancel()
        readTimeoutTask = nil
        for task in snapshotRetryTasks.values { task.cancel() }
        snapshotRetryTasks.removeAll(keepingCapacity: false)
        pendingRead = nil
        inFlightRead = nil

        let provisionalCounts = provisionalTexts.keys.sorted {
            let lhs = provisionalTexts[$0]?.request.observedAt ?? .distantPast
            let rhs = provisionalTexts[$1]?.request.observedAt ?? .distantPast
            return lhs < rhs
        }
        for count in provisionalCounts {
            _ = finalizeProvisionalText(for: count)
        }

        while !imageSaveTasks.isEmpty {
            let tasks = Array(imageSaveTasks.values)
            for task in tasks {
                await task.value
            }
        }

        let abandonedPreparedImages = Array(preparedImages.values)
        preparedImages.removeAll(keepingCapacity: false)
        for item in abandonedPreparedImages {
            await imageDiscarder(item)
        }

        generation &+= 1
        isGracefullyShuttingDown = false
        resetChangeTracking(to: pasteboard.changeCount)
    }

    private func drainPayloadReads(timeout: TimeInterval) async {
        let group = payloadReadGroup
        let boundedTimeout = max(0, timeout)
        await withCheckedContinuation { continuation in
            DispatchQueue.global(qos: .utility).async {
                _ = group.wait(timeout: .now() + boundedTimeout)
                continuation.resume()
            }
        }
    }

    func setConsent(_ newValue: ClipboardMonitoringConsent) {
        invalidatePendingCaptures()
        preferences.setConsent(newValue)
        consent = newValue
        // Every transition establishes a fresh baseline, so earlier content is never captured.
        resetChangeTracking(to: pasteboard.changeCount)
    }

    func setEnabled(_ enabled: Bool) {
        setConsent(enabled ? .enabled : .disabled)
    }

    func setRetentionCount(_ count: Int) {
        preferences.setRetentionCount(count)
        objectWillChange.send()
    }

    func setRetentionDays(_ days: Int) {
        preferences.setRetentionDays(days)
        objectWillChange.send()
    }

    func invalidatePendingCaptures() {
        generation &+= 1
        inFlightRead = nil
        pendingRead = nil
        resetChangeTracking(to: pasteboard.changeCount)
        for task in imageSaveTasks.values { task.cancel() }
    }

    @discardableResult
    func performInternalWrite<Result>(
        _ action: () -> (result: Result, changeCount: Int)
    ) -> Result {
        let (result, internalCount) = action()
        finalizeAndClearSupersededState(currentCount: internalCount)
        changeCount = internalCount
        rememberChangeCount(internalCount)
        if settleReadRequest?.changeCount == internalCount {
            settleReadTask?.cancel()
            settleReadTask = nil
            settleReadRequest = nil
        }
        if pendingRead?.changeCount == internalCount {
            pendingRead = nil
        }
        return result
    }

    func checkClipboard(observedAt: Date = Date()) {
        guard !isStopped, consent == .enabled else { return }
        let currentCount = pasteboard.changeCount
        guard currentCount != changeCount else { return }
        finalizeAndClearSupersededState(currentCount: currentCount)
        changeCount = currentCount
        guard !rememberedChangeCounts.contains(currentCount) else { return }
        scheduleSettledRead(ClipboardReadRequest(
            id: UUID(),
            generation: generation,
            changeCount: currentCount,
            observedAt: observedAt
        ))
    }

    private func enqueueRead(_ request: ClipboardReadRequest) {
        guard !rememberedChangeCounts.contains(request.changeCount),
              inFlightRead?.changeCount != request.changeCount,
              !outstandingReads.values.contains(where: {
                  $0.generation == request.generation && $0.changeCount == request.changeCount
              }) else { return }
        guard inFlightRead == nil else {
            pendingRead = request
            return
        }
        startRead(request)
    }

    private func scheduleSettledRead(_ request: ClipboardReadRequest) {
        guard request.generation == generation,
              consent == .enabled,
              !isStopped,
              !rememberedChangeCounts.contains(request.changeCount) else { return }
        if settleReadRequest?.changeCount == request.changeCount { return }

        settleReadTask?.cancel()
        settleReadRequest = request
        settleReadTask = Task { @MainActor [weak self] in
            try? await Task.sleep(nanoseconds: Self.payloadSettleNanoseconds)
            guard !Task.isCancelled, let self,
                  self.settleReadRequest?.id == request.id else { return }
            self.settleReadTask = nil
            self.settleReadRequest = nil
            guard !self.isStopped,
                  self.consent == .enabled,
                  self.generation == request.generation,
                  !self.rememberedChangeCounts.contains(request.changeCount) else { return }

            let latestCount = self.pasteboard.changeCount
            guard latestCount == request.changeCount else {
                self.finalizeAndClearSupersededState(currentCount: latestCount)
                self.changeCount = latestCount
                if !self.rememberedChangeCounts.contains(latestCount) {
                    self.scheduleSettledRead(ClipboardReadRequest(
                        id: UUID(),
                        generation: self.generation,
                        changeCount: latestCount,
                        observedAt: Date()
                    ))
                }
                return
            }
            self.enqueueRead(request)
        }
    }

    private func resetChangeTracking(to baseline: Int) {
        settleReadTask?.cancel()
        settleReadTask = nil
        settleReadRequest = nil
        readTimeoutTask?.cancel()
        readTimeoutTask = nil
        for task in snapshotRetryTasks.values { task.cancel() }
        snapshotRetryTasks.removeAll(keepingCapacity: true)
        emptySnapshotRetryAttempts.removeAll(keepingCapacity: true)
        pendingFailureMessages.removeAll(keepingCapacity: true)
        provisionalTexts.removeAll(keepingCapacity: true)
        changeCount = baseline
        rememberedChangeCounts.removeAll(keepingCapacity: true)
        rememberedChangeCountOrder.removeAll(keepingCapacity: true)
        rememberChangeCount(baseline)
    }

    private func rememberChangeCount(_ count: Int) {
        let wasInserted = rememberedChangeCounts.insert(count).inserted
        clearTransientState(for: count)
        guard wasInserted else { return }
        rememberedChangeCountOrder.append(count)
        if rememberedChangeCountOrder.count > Self.maximumRememberedChangeCounts {
            let expired = rememberedChangeCountOrder.removeFirst()
            rememberedChangeCounts.remove(expired)
        }
    }

    private func clearTransientState(for count: Int, discardProvisional: Bool = true) {
        snapshotRetryTasks.removeValue(forKey: count)?.cancel()
        emptySnapshotRetryAttempts[count] = nil
        pendingFailureMessages[count] = nil
        if discardProvisional {
            provisionalTexts[count] = nil
        }
    }

    @discardableResult
    private func finalizeProvisionalText(for count: Int) -> Bool {
        guard let provisional = provisionalTexts.removeValue(forKey: count) else { return false }
        rememberChangeCount(count)
        consume(.text(provisional.content), request: provisional.request)
        return true
    }

    private func finalizeAndClearSupersededState(
        currentCount: Int,
        preservingCount: Int? = nil
    ) {
        var protectedCounts = Set(outstandingReads.values.compactMap { request in
            request.generation == generation ? request.changeCount : nil
        })
        if let preservingCount {
            protectedCounts.insert(preservingCount)
        }
        let transientCounts = Set(emptySnapshotRetryAttempts.keys)
            .union(pendingFailureMessages.keys)
            .union(provisionalTexts.keys)
            .union(snapshotRetryTasks.keys)
        let orderedCounts = transientCounts
            .filter { $0 != currentCount && !protectedCounts.contains($0) }
            .sorted {
                let lhs = provisionalTexts[$0]?.request.observedAt ?? .distantPast
                let rhs = provisionalTexts[$1]?.request.observedAt ?? .distantPast
                return lhs < rhs
            }
        for count in orderedCounts where !finalizeProvisionalText(for: count) {
            clearTransientState(for: count)
        }
    }

    private func startRead(_ request: ClipboardReadRequest) {
        guard inFlightRead == nil else {
            pendingRead = request
            return
        }
        guard outstandingReads.count < Self.maximumConcurrentPayloadReads else {
            pendingRead = request
            return
        }
        inFlightRead = request
        outstandingReads[request.id] = request
        readTimeoutTask?.cancel()
        let timeoutNanoseconds = UInt64(readTimeoutInterval * 1_000_000_000)
        readTimeoutTask = Task { @MainActor [weak self] in
            try? await Task.sleep(nanoseconds: timeoutNanoseconds)
            guard !Task.isCancelled, let self else { return }
            self.finishReadTimeout(request)
        }
        let pasteboard = pasteboard
        let maximumImageBytes = Self.maximumImageBytes
        let maximumTextCharacters = Self.maximumTextCharacters
        payloadReadGroup.enter()
        let payloadReadGroup = payloadReadGroup
        payloadReaderQueue.async { [weak self] in
            defer { payloadReadGroup.leave() }
            let snapshot = pasteboard.readPayloadSnapshot(
                maximumImageBytes: maximumImageBytes,
                maximumTextCharacters: maximumTextCharacters
            )
            Task { @MainActor [weak self] in
                self?.finishRead(snapshot, request: request)
            }
        }
    }

    private func finishReadTimeout(_ request: ClipboardReadRequest) {
        guard inFlightRead?.id == request.id else { return }
        inFlightRead = nil
        readTimeoutTask = nil
        guard !isStopped,
              consent == .enabled,
              request.generation == generation else { return }

        if let next = pendingRead {
            pendingRead = nil
            finalizeAndClearSupersededState(currentCount: next.changeCount)
            if next.generation == generation,
               !rememberedChangeCounts.contains(next.changeCount) {
                startRead(next)
                return
            }
        }

        let latestCount = pasteboard.changeCount
        guard latestCount == request.changeCount else {
            finalizeAndClearSupersededState(currentCount: latestCount)
            changeCount = latestCount
            if !rememberedChangeCounts.contains(latestCount) {
                scheduleSettledRead(ClipboardReadRequest(
                    id: UUID(),
                    generation: generation,
                    changeCount: latestCount,
                    observedAt: Date()
                ))
            }
            return
        }
        // The synchronous provider read cannot be cancelled. Leave this count uncommitted so a
        // valid late result can still be accepted exactly once, while newer clipboard counts use
        // another reader lane instead of spawning repeated reads for the same slow provider.
    }

    private func finishRead(_ snapshot: ClipboardPayloadSnapshot?, request: ClipboardReadRequest) {
        outstandingReads[request.id] = nil
        defer { startPendingReadIfPossible() }
        guard inFlightRead?.id == request.id else {
            finishLateRead(snapshot, request: request)
            return
        }
        readTimeoutTask?.cancel()
        readTimeoutTask = nil
        inFlightRead = nil
        guard !isStopped,
              consent == .enabled,
              request.generation == generation else { return }

        let latestPasteboardCount = pasteboard.changeCount
        let discoveredNewCount = latestPasteboardCount != changeCount
        if latestPasteboardCount != changeCount {
            finalizeAndClearSupersededState(
                currentCount: latestPasteboardCount,
                preservingCount: request.changeCount
            )
            changeCount = latestPasteboardCount
        }

        if latestPasteboardCount != request.changeCount,
           snapshot?.changeCount != request.changeCount {
            if !finalizeProvisionalText(for: request.changeCount) {
                clearTransientState(for: request.changeCount)
            }
        }

        var scheduledRetry = false
        if let snapshot,
           snapshot.changeCount == request.changeCount,
           !rememberedChangeCounts.contains(snapshot.changeCount) {
            let effectiveRequest = ClipboardReadRequest(
                id: request.id,
                generation: request.generation,
                changeCount: snapshot.changeCount,
                observedAt: request.observedAt
            )
            switch snapshot.payload {
            case .none:
                if latestPasteboardCount == snapshot.changeCount {
                    scheduledRetry = scheduleEmptySnapshotRetry(
                        changeCount: snapshot.changeCount,
                        generation: request.generation,
                        observedAt: effectiveRequest.observedAt
                    )
                }
            case .pendingImage(let fallbackText, let failureMessage):
                if let fallbackText {
                    provisionalTexts[snapshot.changeCount] = ClipboardProvisionalText(
                        content: fallbackText,
                        request: effectiveRequest
                    )
                }
                if latestPasteboardCount == snapshot.changeCount {
                    scheduledRetry = scheduleEmptySnapshotRetry(
                        changeCount: snapshot.changeCount,
                        generation: request.generation,
                        observedAt: effectiveRequest.observedAt,
                        terminalError: failureMessage
                    )
                } else if !finalizeProvisionalText(for: snapshot.changeCount) {
                    clearTransientState(for: snapshot.changeCount)
                }
            default:
                rememberChangeCount(snapshot.changeCount)
                consume(snapshot.payload, request: effectiveRequest)
            }
        } else if snapshot == nil, latestPasteboardCount == request.changeCount {
            scheduledRetry = scheduleEmptySnapshotRetry(
                changeCount: request.changeCount,
                generation: request.generation,
                observedAt: request.observedAt
            )
        }

        if latestPasteboardCount != request.changeCount,
           !rememberedChangeCounts.contains(request.changeCount) {
            if !finalizeProvisionalText(for: request.changeCount) {
                clearTransientState(for: request.changeCount)
            }
        }

        if let next = pendingRead {
            pendingRead = nil
            if next.generation == generation,
               !rememberedChangeCounts.contains(next.changeCount) {
                startRead(next)
                return
            }
        }

        guard !scheduledRetry,
              !rememberedChangeCounts.contains(latestPasteboardCount),
              snapshotRetryTasks[latestPasteboardCount] == nil else { return }
        let observedAt = discoveredNewCount ? Date() : request.observedAt
        scheduleSettledRead(ClipboardReadRequest(
            id: UUID(),
            generation: generation,
            changeCount: latestPasteboardCount,
            observedAt: observedAt
        ))
    }

    private func finishLateRead(
        _ snapshot: ClipboardPayloadSnapshot?,
        request: ClipboardReadRequest
    ) {
        guard !isStopped,
              consent == .enabled,
              request.generation == generation else { return }

        let latestCount = pasteboard.changeCount
        defer {
            if latestCount != request.changeCount {
                scheduleDiscoveredCountIfNeeded(latestCount)
            }
        }
        guard let snapshot else {
            if latestCount == request.changeCount {
                _ = scheduleEmptySnapshotRetry(
                    changeCount: request.changeCount,
                    generation: request.generation,
                    observedAt: request.observedAt
                )
            } else if !finalizeProvisionalText(for: request.changeCount) {
                clearTransientState(for: request.changeCount)
            }
            return
        }
        guard snapshot.changeCount == request.changeCount else {
            if !finalizeProvisionalText(for: request.changeCount) {
                clearTransientState(for: request.changeCount)
            }
            return
        }
        guard !rememberedChangeCounts.contains(request.changeCount) else { return }
        let effectiveRequest = ClipboardReadRequest(
            id: request.id,
            generation: request.generation,
            changeCount: request.changeCount,
            observedAt: request.observedAt
        )
        switch snapshot.payload {
        case .none:
            if latestCount == snapshot.changeCount {
                _ = scheduleEmptySnapshotRetry(
                    changeCount: snapshot.changeCount,
                    generation: request.generation,
                    observedAt: request.observedAt
                )
            } else if !finalizeProvisionalText(for: request.changeCount) {
                clearTransientState(for: request.changeCount)
            }
        case .pendingImage(let fallbackText, let failureMessage):
            if let fallbackText {
                provisionalTexts[request.changeCount] = ClipboardProvisionalText(
                    content: fallbackText,
                    request: effectiveRequest
                )
            }
            if latestCount == request.changeCount {
                _ = scheduleEmptySnapshotRetry(
                    changeCount: request.changeCount,
                    generation: request.generation,
                    observedAt: request.observedAt,
                    terminalError: failureMessage
                )
            } else if !finalizeProvisionalText(for: request.changeCount) {
                clearTransientState(for: request.changeCount)
            }
        default:
            rememberChangeCount(request.changeCount)
            consume(snapshot.payload, request: effectiveRequest)
        }
    }

    private func startPendingReadIfPossible() {
        guard inFlightRead == nil,
              outstandingReads.count < Self.maximumConcurrentPayloadReads,
              let next = pendingRead else { return }
        pendingRead = nil
        guard !isStopped,
              consent == .enabled,
              next.generation == generation,
              !rememberedChangeCounts.contains(next.changeCount) else { return }
        startRead(next)
    }

    private func scheduleDiscoveredCountIfNeeded(_ discoveredCount: Int) {
        changeCount = discoveredCount
        guard !isStopped,
              consent == .enabled,
              !rememberedChangeCounts.contains(discoveredCount),
              inFlightRead?.changeCount != discoveredCount,
              pendingRead?.changeCount != discoveredCount,
              settleReadRequest?.changeCount != discoveredCount,
              snapshotRetryTasks[discoveredCount] == nil,
              !outstandingReads.values.contains(where: {
                  $0.generation == generation && $0.changeCount == discoveredCount
              }) else { return }
        scheduleSettledRead(ClipboardReadRequest(
            id: UUID(),
            generation: generation,
            changeCount: discoveredCount,
            observedAt: Date()
        ))
    }

    @discardableResult
    private func scheduleEmptySnapshotRetry(
        changeCount: Int,
        generation: UInt64,
        observedAt: Date,
        terminalError: String? = nil
    ) -> Bool {
        if let terminalError {
            pendingFailureMessages[changeCount] = terminalError
        }
        let attempt = (emptySnapshotRetryAttempts[changeCount] ?? 0) + 1
        guard attempt <= Self.maximumEmptySnapshotRetries else {
            let retainedError = pendingFailureMessages[changeCount]
            let finalizedFallback = finalizeProvisionalText(for: changeCount)
            if !finalizedFallback {
                rememberChangeCount(changeCount)
            }
            if let retainedError {
                onError?(retainedError)
            }
            return false
        }
        emptySnapshotRetryAttempts[changeCount] = attempt
        let delayMilliseconds = min(200, 25 << min(attempt - 1, 3))
        scheduleReadRetry(
            changeCount: changeCount,
            generation: generation,
            observedAt: observedAt,
            delayMilliseconds: delayMilliseconds
        )
        return true
    }

    private func scheduleReadRetry(
        changeCount: Int,
        generation: UInt64,
        observedAt: Date,
        delayMilliseconds: Int
    ) {
        pendingRead = pendingRead?.changeCount == changeCount ? nil : pendingRead
        snapshotRetryTasks[changeCount]?.cancel()
        snapshotRetryTasks[changeCount] = Task { @MainActor [weak self] in
            try? await Task.sleep(nanoseconds: UInt64(delayMilliseconds) * 1_000_000)
            guard !Task.isCancelled, let self else { return }
            self.snapshotRetryTasks[changeCount] = nil
            guard !self.isStopped,
                  self.consent == .enabled,
                  self.generation == generation else {
                self.clearTransientState(for: changeCount)
                return
            }
            let latestCount = self.pasteboard.changeCount
            guard latestCount == changeCount,
                  !self.rememberedChangeCounts.contains(changeCount) else {
                if latestCount != changeCount {
                    self.finalizeAndClearSupersededState(currentCount: latestCount)
                } else {
                    self.clearTransientState(for: changeCount)
                }
                return
            }
            self.enqueueRead(ClipboardReadRequest(
                id: UUID(),
                generation: generation,
                changeCount: changeCount,
                observedAt: observedAt
            ))
        }
    }

    private func consume(_ payload: ClipboardPayloadRead, request: ClipboardReadRequest) {
        switch payload {
        case .none:
            break
        case .ignored:
            break
        case .pendingImage:
            break
        case .rejected(let message):
            onError?(message)
        case .text(let content):
            let scheme = URL(string: content)?.scheme?.lowercased()
            let type: ItemType = scheme == "http" || scheme == "https" ? .url : .text
            let preview = content.count > 200 ? String(content.prefix(200)) + "..." : content
            onNewItem?(StashItem(
                type: type,
                content: content,
                preview: preview,
                createdAt: request.observedAt,
                managedOrigin: .clipboard
            ))
        case .image(let data, let fileExtension):
            saveImage(data, fileExtension: fileExtension, request: request)
        }
    }

    func prepareImageRecord(
        data: Data,
        fileExtension: String = "png",
        observedAt: Date = Date()
    ) async throws -> StashItem {
        let savedItem = try await imageSaver(data, fileExtension, observedAt)
        guard !Task.isCancelled else {
            await imageDiscarder(savedItem)
            throw CancellationError()
        }
        let prepared = clipboardImageItem(from: savedItem, observedAt: observedAt)
        preparedImages[prepared.id] = prepared
        return prepared
    }

    @discardableResult
    func commitPreparedImageRecord(_ item: StashItem) -> Bool {
        guard preparedImages[item.id] != nil, let onNewItem else { return false }
        preparedImages[item.id] = nil
        onNewItem(item)
        return true
    }

    func discardPreparedImageRecord(_ item: StashItem) async {
        guard preparedImages.removeValue(forKey: item.id) != nil else { return }
        await imageDiscarder(item)
    }

    private func saveImage(
        _ data: Data,
        fileExtension: String,
        request: ClipboardReadRequest
    ) {
        let taskID = UUID()
        let task = Task { [weak self] in
            guard let self else { return }
            var finalError: Error = CocoaError(.fileWriteUnknown)
            for attempt in 0...Self.maximumImageSaveRetries {
                guard !Task.isCancelled else { break }
                do {
                    let savedItem = try await imageSaver(data, fileExtension, request.observedAt)
                    let wasCancelled = Task.isCancelled
                    await finishImageSave(
                        savedItem,
                        request: request,
                        taskID: taskID,
                        wasCancelled: wasCancelled
                    )
                    return
                } catch {
                    finalError = error
                    guard !Task.isCancelled, attempt < Self.maximumImageSaveRetries else { break }
                    do {
                        try await Task.sleep(nanoseconds: UInt64(100 * (attempt + 1)) * 1_000_000)
                    } catch {
                        break
                    }
                }
            }
            finishImageSaveFailure(finalError, request: request, taskID: taskID)
        }
        imageSaveTasks[taskID] = task
    }

    private func finishImageSave(
        _ savedItem: StashItem,
        request: ClipboardReadRequest,
        taskID: UUID,
        wasCancelled: Bool
    ) async {
        imageSaveTasks[taskID] = nil
        let isCurrent = !wasCancelled
            && (!isStopped || isGracefullyShuttingDown)
            && consent == .enabled
            && request.generation == generation
        guard isCurrent else {
            await imageDiscarder(savedItem)
            return
        }
        onNewItem?(clipboardImageItem(from: savedItem, observedAt: request.observedAt))
    }

    private func finishImageSaveFailure(
        _ error: Error,
        request: ClipboardReadRequest,
        taskID: UUID
    ) {
        imageSaveTasks[taskID] = nil
        guard (!isStopped || isGracefullyShuttingDown),
              consent == .enabled,
              request.generation == generation else { return }
        onError?("保存剪贴板图片失败：\(error.localizedDescription)")
    }

    private func clipboardImageItem(from item: StashItem, observedAt: Date) -> StashItem {
        StashItem(
            id: item.id,
            type: .image,
            content: item.content,
            preview: item.preview,
            createdAt: observedAt,
            isPinned: item.isPinned,
            availability: item.availability,
            managedOrigin: .clipboard
        )
    }
}
