import Foundation
import AppKit

enum ClipboardMonitoringConsent: String, CaseIterable, Sendable {
    case undecided
    case enabled
    case disabled
}

@MainActor
final class ClipboardPreferences: ObservableObject {
    static let shared = ClipboardPreferences()

    private enum Key {
        static let consent = "clipboardMonitoringConsent"
        static let legacyEnabled = "clipboardMonitoringEnabled"
        static let retentionCount = "clipboardRetentionCount"
        static let retentionDays = "clipboardRetentionDays"
    }

    private let defaults: UserDefaults
    @Published private(set) var consent: ClipboardMonitoringConsent
    @Published private(set) var retentionCount: Int
    @Published private(set) var retentionDays: Int

    init(defaults: UserDefaults = .standard) {
        self.defaults = defaults
        if let rawConsent = defaults.string(forKey: Key.consent),
           let storedConsent = ClipboardMonitoringConsent(rawValue: rawConsent) {
            consent = storedConsent
        } else if let legacyEnabled = defaults.object(forKey: Key.legacyEnabled) as? Bool {
            let migratedConsent: ClipboardMonitoringConsent = legacyEnabled ? .enabled : .disabled
            consent = migratedConsent
            defaults.set(migratedConsent.rawValue, forKey: Key.consent)
            defaults.removeObject(forKey: Key.legacyEnabled)
        } else {
            consent = .undecided
        }

        let storedCount = defaults.object(forKey: Key.retentionCount) as? Int
        retentionCount = storedCount.flatMap { [0, 50, 100, 200].contains($0) ? $0 : nil } ?? 100
        let storedDays = defaults.object(forKey: Key.retentionDays) as? Int
        retentionDays = storedDays.flatMap { [0, 1, 7, 30].contains($0) ? $0 : nil } ?? 30
    }

    var retentionPolicy: ClipboardRetentionPolicy {
        ClipboardRetentionPolicy(
            maximumItemCount: retentionCount == 0 ? nil : retentionCount,
            maximumAgeDays: retentionDays == 0 ? nil : retentionDays
        )
    }

    func setConsent(_ newValue: ClipboardMonitoringConsent) {
        consent = newValue
        defaults.set(newValue.rawValue, forKey: Key.consent)
    }

    func setRetentionCount(_ count: Int) {
        guard [0, 50, 100, 200].contains(count) else { return }
        retentionCount = count
        defaults.set(count, forKey: Key.retentionCount)
    }

    func setRetentionDays(_ days: Int) {
        guard [0, 1, 7, 30].contains(days) else { return }
        retentionDays = days
        defaults.set(days, forKey: Key.retentionDays)
    }
}

enum ClipboardPayloadRead: Sendable {
    case none
    case ignored
    case text(String)
    case image(Data, fileExtension: String)
    case rejected(String)
}

struct ClipboardPayloadSnapshot: Sendable {
    let changeCount: Int
    let payload: ClipboardPayloadRead
}

protocol ClipboardPasteboard: Sendable {
    @MainActor var changeCount: Int { get }
    func readPayloadSnapshot(
        maximumImageBytes: Int,
        maximumTextCharacters: Int
    ) -> ClipboardPayloadSnapshot?
}

final class SystemClipboardPasteboard: ClipboardPasteboard, @unchecked Sendable {
    static let shared = SystemClipboardPasteboard()
    private static let ignoredTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType")
    ]
    private let pasteboard: NSPasteboard

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    @MainActor var changeCount: Int { pasteboard.changeCount }

    func readPayloadSnapshot(
        maximumImageBytes: Int,
        maximumTextCharacters: Int
    ) -> ClipboardPayloadSnapshot? {
        // Providers can update the pasteboard while materializing data. Retry a changing read so
        // every accepted payload is tied to the exact stable changeCount that produced it.
        for _ in 0..<3 {
            let before = pasteboard.changeCount
            let beforeTypes = pasteboard.types?.map(\.rawValue).sorted() ?? []
            let payload = readPayload(
                maximumImageBytes: maximumImageBytes,
                maximumTextCharacters: maximumTextCharacters
            )
            let after = pasteboard.changeCount
            let afterTypes = pasteboard.types?.map(\.rawValue).sorted() ?? []
            if before == after, beforeTypes == afterTypes {
                return ClipboardPayloadSnapshot(changeCount: after, payload: payload)
            }
        }
        return nil
    }

    private func readPayload(
        maximumImageBytes: Int,
        maximumTextCharacters: Int
    ) -> ClipboardPayloadRead {
        guard pasteboard.availableType(from: Self.ignoredTypes) == nil else { return .ignored }

        // NSPasteboard has no reliable size-only preflight API. Materialization happens on the
        // dedicated utility queue, one provider at a time, before applying the hard limit.
        let declaredTypes = Set(pasteboard.types ?? [])
        if declaredTypes.contains(.png) {
            guard let pngData = pasteboard.data(forType: .png) else { return .none }
            return pngData.count <= maximumImageBytes
                ? .image(pngData, fileExtension: "png")
                : .rejected("剪贴板图片超过 50 MB，已跳过")
        }
        if declaredTypes.contains(.tiff) {
            guard let tiffData = pasteboard.data(forType: .tiff) else { return .none }
            return tiffData.count <= maximumImageBytes
                ? .image(tiffData, fileExtension: "tiff")
                : .rejected("剪贴板图片超过 50 MB，已跳过")
        }
        if let content = pasteboard.string(forType: .URL)
            ?? pasteboard.string(forType: .string),
           !content.isEmpty {
            return content.count <= maximumTextCharacters
                ? .text(content)
                : .rejected("剪贴板文本超过 100 万字符，已跳过")
        }
        return .none
    }
}

typealias ClipboardImageSaver = @Sendable (Data, String, Date) async throws -> StashItem
typealias ClipboardImageDiscarder = @Sendable (StashItem) async -> Void

private struct ClipboardReadRequest: Sendable, Equatable {
    let id: UUID
    let generation: UInt64
    let changeCount: Int
    let observedAt: Date
}

private struct ClipboardProvisionalText: Sendable {
    let content: String
    let request: ClipboardReadRequest
}

@MainActor
final class ClipboardMonitor: ObservableObject {
    static let shared = ClipboardMonitor()
    private static let maximumImageBytes = 50 * 1024 * 1024
    private static let maximumTextCharacters = 1_000_000
    private static let maximumRememberedChangeCounts = 256
    private static let maximumEmptySnapshotRetries = 6
    private static let maximumReadTimeoutRetries = 2
    private static let maximumTextConfirmationRetries = 4
    private static let payloadSettleNanoseconds: UInt64 = 25_000_000

    private let preferences: ClipboardPreferences
    private let pasteboard: ClipboardPasteboard
    private let imageSaver: ClipboardImageSaver
    private let imageDiscarder: ClipboardImageDiscarder
    private let payloadReaderQueue: DispatchQueue
    private let payloadReadGroup = DispatchGroup()
    private let pollingInterval: TimeInterval
    private let readTimeoutInterval: TimeInterval
    private var changeCount: Int
    private var generation: UInt64 = 0
    private var inFlightRead: ClipboardReadRequest?
    private var pendingRead: ClipboardReadRequest?
    private var settleReadRequest: ClipboardReadRequest?
    private var settleReadTask: Task<Void, Never>?
    private var readTimeoutTask: Task<Void, Never>?
    private var imageSaveTasks: [UUID: Task<Void, Never>] = [:]
    private var rememberedChangeCounts = Set<Int>()
    private var rememberedChangeCountOrder: [Int] = []
    private var emptySnapshotRetryAttempts: [Int: Int] = [:]
    private var snapshotRetryTasks: [Int: Task<Void, Never>] = [:]
    private var readTimeoutAttempts: [Int: Int] = [:]
    private var textConfirmationAttempts: [Int: Int] = [:]
    private var provisionalTexts: [Int: ClipboardProvisionalText] = [:]
    private var preparedImages: [UUID: StashItem] = [:]
    private var timer: Timer?
    private var isStopped = false
    private var isGracefullyShuttingDown = false
    var onNewItem: ((StashItem) -> Void)?
    var onError: ((String) -> Void)?
    @Published private(set) var consent: ClipboardMonitoringConsent

    var isEnabled: Bool { consent == .enabled }

    init(
        preferences: ClipboardPreferences? = nil,
        pasteboard: ClipboardPasteboard? = nil,
        payloadReaderQueue: DispatchQueue? = nil,
        pollingInterval: TimeInterval = 0.25,
        readTimeoutInterval: TimeInterval = 2,
        imageSaver: ClipboardImageSaver? = nil,
        imageDiscarder: ClipboardImageDiscarder? = nil
    ) {
        let resolvedPreferences = preferences ?? ClipboardPreferences.shared
        let resolvedPasteboard = pasteboard ?? SystemClipboardPasteboard.shared
        self.preferences = resolvedPreferences
        self.pasteboard = resolvedPasteboard
        self.payloadReaderQueue = payloadReaderQueue ?? DispatchQueue(
            label: "com.quickstash.clipboard-reader",
            qos: .utility,
            attributes: .concurrent
        )
        self.pollingInterval = max(0.05, pollingInterval)
        self.readTimeoutInterval = max(0.05, readTimeoutInterval)
        self.imageSaver = imageSaver ?? { data, fileExtension, observedAt in
            try await QuickStashFileManager.shared.saveClipboardImage(
                data: data,
                fileExtension: fileExtension,
                createdAt: observedAt
            )
        }
        self.imageDiscarder = imageDiscarder ?? { item in
            await QuickStashFileManager.shared.discardUnregisteredClipboardImage(at: item.content)
        }
        consent = resolvedPreferences.consent
        changeCount = resolvedPasteboard.changeCount
        rememberChangeCount(changeCount)
    }

    var retentionPolicy: ClipboardRetentionPolicy { preferences.retentionPolicy }
    var retentionCount: Int { preferences.retentionCount }
    var retentionDays: Int { preferences.retentionDays }

    func startMonitoring() {
        guard timer == nil else { return }
        let wasStopped = isStopped
        isStopped = false
        if wasStopped {
            resetChangeTracking(to: pasteboard.changeCount)
        }
        let timer = Timer(timeInterval: pollingInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.checkClipboard() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stopMonitoring() {
        isStopped = true
        timer?.invalidate()
        timer = nil
        invalidatePendingCaptures()
    }

    func shutdownAndDrain(waitForPayloadReads: Bool = false) async {
        stopMonitoring()
        if waitForPayloadReads {
            await drainPayloadReads()
        }
        while !imageSaveTasks.isEmpty {
            let tasks = Array(imageSaveTasks.values)
            for task in tasks {
                await task.value
            }
        }
        let abandonedPreparedImages = Array(preparedImages.values)
        preparedImages.removeAll(keepingCapacity: false)
        for item in abandonedPreparedImages {
            await imageDiscarder(item)
        }
    }

    func shutdownForTermination(
        settleNanoseconds: UInt64 = 400_000_000
    ) async {
        guard !isStopped else {
            await shutdownAndDrain()
            return
        }

        // Stop periodic polling, but give the final observed pasteboard change a short async
        // window to materialize. This never blocks MainActor or waits indefinitely on a provider.
        timer?.invalidate()
        timer = nil
        checkClipboard()
        if settleNanoseconds > 0 {
            try? await Task.sleep(nanoseconds: settleNanoseconds)
        }

        isGracefullyShuttingDown = true
        isStopped = true
        settleReadTask?.cancel()
        settleReadTask = nil
        settleReadRequest = nil
        readTimeoutTask?.cancel()
        readTimeoutTask = nil
        for task in snapshotRetryTasks.values { task.cancel() }
        snapshotRetryTasks.removeAll(keepingCapacity: false)
        pendingRead = nil
        inFlightRead = nil

        let provisionalCounts = provisionalTexts.keys.sorted {
            let lhs = provisionalTexts[$0]?.request.observedAt ?? .distantPast
            let rhs = provisionalTexts[$1]?.request.observedAt ?? .distantPast
            return lhs < rhs
        }
        for count in provisionalCounts {
            _ = finalizeProvisionalText(for: count)
        }

        while !imageSaveTasks.isEmpty {
            let tasks = Array(imageSaveTasks.values)
            for task in tasks {
                await task.value
            }
        }

        let abandonedPreparedImages = Array(preparedImages.values)
        preparedImages.removeAll(keepingCapacity: false)
        for item in abandonedPreparedImages {
            await imageDiscarder(item)
        }

        generation &+= 1
        isGracefullyShuttingDown = false
        resetChangeTracking(to: pasteboard.changeCount)
    }

    private func drainPayloadReads() async {
        await withCheckedContinuation { continuation in
            payloadReadGroup.notify(queue: .global(qos: .utility)) {
                continuation.resume()
            }
        }
    }

    func setConsent(_ newValue: ClipboardMonitoringConsent) {
        invalidatePendingCaptures()
        preferences.setConsent(newValue)
        consent = newValue
        // Every transition establishes a fresh baseline, so earlier content is never captured.
        resetChangeTracking(to: pasteboard.changeCount)
    }

    func setEnabled(_ enabled: Bool) {
        setConsent(enabled ? .enabled : .disabled)
    }

    func setRetentionCount(_ count: Int) {
        preferences.setRetentionCount(count)
        objectWillChange.send()
    }

    func setRetentionDays(_ days: Int) {
        preferences.setRetentionDays(days)
        objectWillChange.send()
    }

    func invalidatePendingCaptures() {
        generation &+= 1
        inFlightRead = nil
        pendingRead = nil
        resetChangeTracking(to: pasteboard.changeCount)
        for task in imageSaveTasks.values { task.cancel() }
    }

    @discardableResult
    func performInternalWrite<Result>(
        _ action: () -> (result: Result, changeCount: Int)
    ) -> Result {
        let (result, internalCount) = action()
        finalizeAndClearSupersededState(currentCount: internalCount)
        changeCount = internalCount
        rememberChangeCount(internalCount)
        if settleReadRequest?.changeCount == internalCount {
            settleReadTask?.cancel()
            settleReadTask = nil
            settleReadRequest = nil
        }
        if pendingRead?.changeCount == internalCount {
            pendingRead = nil
        }
        return result
    }

    func checkClipboard(observedAt: Date = Date()) {
        guard !isStopped, consent == .enabled else { return }
        let currentCount = pasteboard.changeCount
        guard currentCount != changeCount else { return }
        finalizeAndClearSupersededState(currentCount: currentCount)
        changeCount = currentCount
        guard !rememberedChangeCounts.contains(currentCount) else { return }
        scheduleSettledRead(ClipboardReadRequest(
            id: UUID(),
            generation: generation,
            changeCount: currentCount,
            observedAt: observedAt
        ))
    }

    private func enqueueRead(_ request: ClipboardReadRequest) {
        guard !rememberedChangeCounts.contains(request.changeCount),
              inFlightRead?.changeCount != request.changeCount else { return }
        guard inFlightRead == nil else {
            pendingRead = request
            return
        }
        startRead(request)
    }

    private func scheduleSettledRead(_ request: ClipboardReadRequest) {
        guard request.generation == generation,
              consent == .enabled,
              !isStopped,
              !rememberedChangeCounts.contains(request.changeCount) else { return }
        if settleReadRequest?.changeCount == request.changeCount { return }

        settleReadTask?.cancel()
        settleReadRequest = request
        settleReadTask = Task { @MainActor [weak self] in
            try? await Task.sleep(nanoseconds: Self.payloadSettleNanoseconds)
            guard !Task.isCancelled, let self,
                  self.settleReadRequest?.id == request.id else { return }
            self.settleReadTask = nil
            self.settleReadRequest = nil
            guard !self.isStopped,
                  self.consent == .enabled,
                  self.generation == request.generation,
                  !self.rememberedChangeCounts.contains(request.changeCount) else { return }

            let latestCount = self.pasteboard.changeCount
            guard latestCount == request.changeCount else {
                self.finalizeAndClearSupersededState(currentCount: latestCount)
                self.changeCount = latestCount
                if !self.rememberedChangeCounts.contains(latestCount) {
                    self.scheduleSettledRead(ClipboardReadRequest(
                        id: UUID(),
                        generation: self.generation,
                        changeCount: latestCount,
                        observedAt: Date()
                    ))
                }
                return
            }
            self.enqueueRead(request)
        }
    }

    private func resetChangeTracking(to baseline: Int) {
        settleReadTask?.cancel()
        settleReadTask = nil
        settleReadRequest = nil
        readTimeoutTask?.cancel()
        readTimeoutTask = nil
        for task in snapshotRetryTasks.values { task.cancel() }
        snapshotRetryTasks.removeAll(keepingCapacity: true)
        emptySnapshotRetryAttempts.removeAll(keepingCapacity: true)
        readTimeoutAttempts.removeAll(keepingCapacity: true)
        textConfirmationAttempts.removeAll(keepingCapacity: true)
        provisionalTexts.removeAll(keepingCapacity: true)
        changeCount = baseline
        rememberedChangeCounts.removeAll(keepingCapacity: true)
        rememberedChangeCountOrder.removeAll(keepingCapacity: true)
        rememberChangeCount(baseline)
    }

    private func rememberChangeCount(_ count: Int) {
        let wasInserted = rememberedChangeCounts.insert(count).inserted
        clearTransientState(for: count)
        guard wasInserted else { return }
        rememberedChangeCountOrder.append(count)
        if rememberedChangeCountOrder.count > Self.maximumRememberedChangeCounts {
            let expired = rememberedChangeCountOrder.removeFirst()
            rememberedChangeCounts.remove(expired)
        }
    }

    private func clearTransientState(for count: Int, discardProvisional: Bool = true) {
        snapshotRetryTasks.removeValue(forKey: count)?.cancel()
        emptySnapshotRetryAttempts[count] = nil
        readTimeoutAttempts[count] = nil
        textConfirmationAttempts[count] = nil
        if discardProvisional {
            provisionalTexts[count] = nil
        }
    }

    @discardableResult
    private func finalizeProvisionalText(for count: Int) -> Bool {
        guard let provisional = provisionalTexts.removeValue(forKey: count) else { return false }
        rememberChangeCount(count)
        consume(.text(provisional.content), request: provisional.request)
        return true
    }

    private func finalizeAndClearSupersededState(
        currentCount: Int,
        preservingCount: Int? = nil
    ) {
        let protectedCount = preservingCount ?? inFlightRead?.changeCount
        let transientCounts = Set(emptySnapshotRetryAttempts.keys)
            .union(readTimeoutAttempts.keys)
            .union(textConfirmationAttempts.keys)
            .union(provisionalTexts.keys)
            .union(snapshotRetryTasks.keys)
        let orderedCounts = transientCounts
            .filter { $0 != currentCount && $0 != protectedCount }
            .sorted {
                let lhs = provisionalTexts[$0]?.request.observedAt ?? .distantPast
                let rhs = provisionalTexts[$1]?.request.observedAt ?? .distantPast
                return lhs < rhs
            }
        for count in orderedCounts where !finalizeProvisionalText(for: count) {
            clearTransientState(for: count)
        }
    }

    private func startRead(_ request: ClipboardReadRequest) {
        inFlightRead = request
        readTimeoutTask?.cancel()
        let timeoutNanoseconds = UInt64(readTimeoutInterval * 1_000_000_000)
        readTimeoutTask = Task { @MainActor [weak self] in
            try? await Task.sleep(nanoseconds: timeoutNanoseconds)
            guard !Task.isCancelled, let self else { return }
            self.finishReadTimeout(request)
        }
        let pasteboard = pasteboard
        let maximumImageBytes = Self.maximumImageBytes
        let maximumTextCharacters = Self.maximumTextCharacters
        payloadReadGroup.enter()
        let payloadReadGroup = payloadReadGroup
        payloadReaderQueue.async { [weak self] in
            defer { payloadReadGroup.leave() }
            let snapshot = pasteboard.readPayloadSnapshot(
                maximumImageBytes: maximumImageBytes,
                maximumTextCharacters: maximumTextCharacters
            )
            Task { @MainActor [weak self] in
                self?.finishRead(snapshot, request: request)
            }
        }
    }

    private func finishReadTimeout(_ request: ClipboardReadRequest) {
        guard inFlightRead?.id == request.id else { return }
        inFlightRead = nil
        readTimeoutTask = nil
        guard !isStopped,
              consent == .enabled,
              request.generation == generation else { return }

        if let next = pendingRead {
            pendingRead = nil
            finalizeAndClearSupersededState(currentCount: next.changeCount)
            readTimeoutAttempts[request.changeCount] = nil
            if next.generation == generation,
               !rememberedChangeCounts.contains(next.changeCount) {
                startRead(next)
                return
            }
        }

        let latestCount = pasteboard.changeCount
        guard latestCount == request.changeCount else {
            finalizeAndClearSupersededState(currentCount: latestCount)
            changeCount = latestCount
            if !rememberedChangeCounts.contains(latestCount) {
                scheduleSettledRead(ClipboardReadRequest(
                    id: UUID(),
                    generation: generation,
                    changeCount: latestCount,
                    observedAt: Date()
                ))
            }
            return
        }

        if finalizeProvisionalText(for: request.changeCount) {
            return
        }

        let attempt = (readTimeoutAttempts[request.changeCount] ?? 0) + 1
        guard attempt <= Self.maximumReadTimeoutRetries else {
            rememberChangeCount(request.changeCount)
            onError?("读取剪贴板内容超时，已跳过本次复制")
            return
        }
        readTimeoutAttempts[request.changeCount] = attempt
        scheduleReadRetry(
            changeCount: request.changeCount,
            generation: request.generation,
            observedAt: request.observedAt,
            delayMilliseconds: 100
        )
    }

    private func finishRead(_ snapshot: ClipboardPayloadSnapshot?, request: ClipboardReadRequest) {
        guard inFlightRead?.id == request.id else { return }
        readTimeoutTask?.cancel()
        readTimeoutTask = nil
        inFlightRead = nil
        guard !isStopped,
              consent == .enabled,
              request.generation == generation else { return }

        let latestPasteboardCount = pasteboard.changeCount
        let discoveredNewCount = latestPasteboardCount != changeCount
        if latestPasteboardCount != changeCount {
            finalizeAndClearSupersededState(
                currentCount: latestPasteboardCount,
                preservingCount: request.changeCount
            )
            changeCount = latestPasteboardCount
        }

        if latestPasteboardCount != request.changeCount,
           snapshot?.changeCount != request.changeCount {
            if !finalizeProvisionalText(for: request.changeCount) {
                clearTransientState(for: request.changeCount)
            }
        }

        var scheduledRetry = false
        if let snapshot,
           !rememberedChangeCounts.contains(snapshot.changeCount) {
            let effectiveRequest = ClipboardReadRequest(
                id: request.id,
                generation: request.generation,
                changeCount: snapshot.changeCount,
                observedAt: request.observedAt
            )
            switch snapshot.payload {
            case .none:
                if latestPasteboardCount == snapshot.changeCount {
                    scheduledRetry = scheduleEmptySnapshotRetry(
                        changeCount: snapshot.changeCount,
                        generation: request.generation,
                        observedAt: effectiveRequest.observedAt
                    )
                }
            case .text(let content):
                let confirmationAttempt = textConfirmationAttempts[snapshot.changeCount] ?? 0
                if latestPasteboardCount == snapshot.changeCount,
                   confirmationAttempt < Self.maximumTextConfirmationRetries {
                    let nextAttempt = confirmationAttempt + 1
                    textConfirmationAttempts[snapshot.changeCount] = nextAttempt
                    provisionalTexts[snapshot.changeCount] = ClipboardProvisionalText(
                        content: content,
                        request: effectiveRequest
                    )
                    scheduleReadRetry(
                        changeCount: snapshot.changeCount,
                        generation: request.generation,
                        observedAt: effectiveRequest.observedAt,
                        delayMilliseconds: min(100, 25 << (nextAttempt - 1))
                    )
                    scheduledRetry = true
                } else {
                    rememberChangeCount(snapshot.changeCount)
                    consume(snapshot.payload, request: effectiveRequest)
                }
            default:
                rememberChangeCount(snapshot.changeCount)
                consume(snapshot.payload, request: effectiveRequest)
            }
        } else if snapshot == nil, latestPasteboardCount == request.changeCount {
            scheduledRetry = scheduleEmptySnapshotRetry(
                changeCount: request.changeCount,
                generation: request.generation,
                observedAt: request.observedAt
            )
        }

        if latestPasteboardCount != request.changeCount,
           !rememberedChangeCounts.contains(request.changeCount) {
            if !finalizeProvisionalText(for: request.changeCount) {
                clearTransientState(for: request.changeCount)
            }
        }

        if let next = pendingRead {
            pendingRead = nil
            if next.generation == generation,
               !rememberedChangeCounts.contains(next.changeCount) {
                startRead(next)
                return
            }
        }

        guard !scheduledRetry,
              !rememberedChangeCounts.contains(latestPasteboardCount),
              snapshotRetryTasks[latestPasteboardCount] == nil else { return }
        let observedAt = discoveredNewCount ? Date() : request.observedAt
        scheduleSettledRead(ClipboardReadRequest(
            id: UUID(),
            generation: generation,
            changeCount: latestPasteboardCount,
            observedAt: observedAt
        ))
    }

    @discardableResult
    private func scheduleEmptySnapshotRetry(
        changeCount: Int,
        generation: UInt64,
        observedAt: Date
    ) -> Bool {
        let attempt = (emptySnapshotRetryAttempts[changeCount] ?? 0) + 1
        guard attempt <= Self.maximumEmptySnapshotRetries else {
            if !finalizeProvisionalText(for: changeCount) {
                rememberChangeCount(changeCount)
            }
            return false
        }
        emptySnapshotRetryAttempts[changeCount] = attempt
        let delayMilliseconds = min(200, 25 << min(attempt - 1, 3))
        scheduleReadRetry(
            changeCount: changeCount,
            generation: generation,
            observedAt: observedAt,
            delayMilliseconds: delayMilliseconds
        )
        return true
    }

    private func scheduleReadRetry(
        changeCount: Int,
        generation: UInt64,
        observedAt: Date,
        delayMilliseconds: Int
    ) {
        pendingRead = pendingRead?.changeCount == changeCount ? nil : pendingRead
        snapshotRetryTasks[changeCount]?.cancel()
        snapshotRetryTasks[changeCount] = Task { @MainActor [weak self] in
            try? await Task.sleep(nanoseconds: UInt64(delayMilliseconds) * 1_000_000)
            guard !Task.isCancelled, let self else { return }
            self.snapshotRetryTasks[changeCount] = nil
            guard !self.isStopped,
                  self.consent == .enabled,
                  self.generation == generation else {
                self.clearTransientState(for: changeCount)
                return
            }
            let latestCount = self.pasteboard.changeCount
            guard latestCount == changeCount,
                  !self.rememberedChangeCounts.contains(changeCount) else {
                if latestCount != changeCount {
                    self.finalizeAndClearSupersededState(currentCount: latestCount)
                } else {
                    self.clearTransientState(for: changeCount)
                }
                return
            }
            self.enqueueRead(ClipboardReadRequest(
                id: UUID(),
                generation: generation,
                changeCount: changeCount,
                observedAt: observedAt
            ))
        }
    }

    private func consume(_ payload: ClipboardPayloadRead, request: ClipboardReadRequest) {
        switch payload {
        case .none:
            break
        case .ignored:
            break
        case .rejected(let message):
            onError?(message)
        case .text(let content):
            let scheme = URL(string: content)?.scheme?.lowercased()
            let type: ItemType = scheme == "http" || scheme == "https" ? .url : .text
            let preview = content.count > 200 ? String(content.prefix(200)) + "..." : content
            onNewItem?(StashItem(
                type: type,
                content: content,
                preview: preview,
                createdAt: request.observedAt,
                managedOrigin: .clipboard
            ))
        case .image(let data, let fileExtension):
            saveImage(data, fileExtension: fileExtension, request: request)
        }
    }

    func prepareImageRecord(
        data: Data,
        fileExtension: String = "png",
        observedAt: Date = Date()
    ) async throws -> StashItem {
        let savedItem = try await imageSaver(data, fileExtension, observedAt)
        guard !Task.isCancelled else {
            await imageDiscarder(savedItem)
            throw CancellationError()
        }
        let prepared = clipboardImageItem(from: savedItem, observedAt: observedAt)
        preparedImages[prepared.id] = prepared
        return prepared
    }

    @discardableResult
    func commitPreparedImageRecord(_ item: StashItem) -> Bool {
        guard preparedImages[item.id] != nil, let onNewItem else { return false }
        preparedImages[item.id] = nil
        onNewItem(item)
        return true
    }

    func discardPreparedImageRecord(_ item: StashItem) async {
        guard preparedImages.removeValue(forKey: item.id) != nil else { return }
        await imageDiscarder(item)
    }

    private func saveImage(
        _ data: Data,
        fileExtension: String,
        request: ClipboardReadRequest
    ) {
        let taskID = UUID()
        let task = Task { [weak self] in
            guard let self else { return }
            do {
                let savedItem = try await imageSaver(data, fileExtension, request.observedAt)
                let wasCancelled = Task.isCancelled
                await finishImageSave(
                    savedItem,
                    request: request,
                    taskID: taskID,
                    wasCancelled: wasCancelled
                )
            } catch {
                finishImageSaveFailure(error, request: request, taskID: taskID)
            }
        }
        imageSaveTasks[taskID] = task
    }

    private func finishImageSave(
        _ savedItem: StashItem,
        request: ClipboardReadRequest,
        taskID: UUID,
        wasCancelled: Bool
    ) async {
        imageSaveTasks[taskID] = nil
        let isCurrent = !wasCancelled
            && (!isStopped || isGracefullyShuttingDown)
            && consent == .enabled
            && request.generation == generation
        guard isCurrent else {
            await imageDiscarder(savedItem)
            return
        }
        onNewItem?(clipboardImageItem(from: savedItem, observedAt: request.observedAt))
    }

    private func finishImageSaveFailure(
        _ error: Error,
        request: ClipboardReadRequest,
        taskID: UUID
    ) {
        imageSaveTasks[taskID] = nil
        guard (!isStopped || isGracefullyShuttingDown),
              consent == .enabled,
              request.generation == generation else { return }
        onError?("保存剪贴板图片失败：\(error.localizedDescription)")
    }

    private func clipboardImageItem(from item: StashItem, observedAt: Date) -> StashItem {
        StashItem(
            id: item.id,
            type: .image,
            content: item.content,
            preview: item.preview,
            createdAt: observedAt,
            isPinned: item.isPinned,
            availability: item.availability,
            managedOrigin: .clipboard
        )
    }
}
